version: "3"

x-shared: &shared  
  image: registry.local/websites
  deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 256M
  restart: always
  healthcheck:
    interval: 10s
    timeout: 2s
    test: lsof -i :443 || exit 1
  depends_on:
    mariadb:
      condition: service_healthy
    redis:
      condition: service_healthy

  butts-are.cool:
    <<: *shared
    container_name: butts-are.cool
    volumes:
      - ./src/config/ssl:/app/ssl
      - /etc/hostname:/data/hostname:ro
      - ./data/shared:/data
      - ./src/sites/butts-are.cool/views:/app/views
      - ./data/cache/butts-are.cool:/data/cache
      - /var/www/sites/butts-are.cool:/app/public
      - /var/www/screenshots:/data/screenshots
    environment:
      SITE: butts-are.cool
    hostname: butts-are-cool.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.2
  furry.cool:
    <<: *shared
    container_name: furry.cool
    volumes:
      - ./src/config/ssl:/app/ssl
      - /etc/hostname:/data/hostname:ro
      - ./data/shared:/data
      - ./src/sites/furry.cool/views:/app/views
      - ./data/cache/furry.cool:/data/cache
      - /var/www/sites/furry.cool:/app/public
      - /var/www/screenshots:/data/screenshots
    environment:
      SITE: furry.cool
    hostname: furry-cool.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.3
  maid.gay:
    <<: *shared
    container_name: maid.gay
    volumes:
      - ./src/config/ssl:/app/ssl
      - /etc/hostname:/data/hostname:ro
      - ./data/shared:/data
      - ./src/sites/maid.gay/views:/app/views
      - ./data/cache/maid.gay:/data/cache
      - /var/www/sites/maid.gay:/app/public
    environment:
      SITE: maid.gay
    hostname: maid-gay.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.4
  yiff.media:
    <<: *shared
    container_name: yiff.media
    volumes:
      - ./src/config/ssl:/app/ssl
      - /etc/hostname:/data/hostname:ro
      - ./data/shared:/data
      - ./src/sites/yiff.media/views:/app/views
      - ./data/cache/yiff.media:/data/cache
      - /var/www/sites/yiff.media:/app/public
      - /var/www/e621-thumbnails:/data/e621-thumbnails
    environment:
      SITE: yiff.media
    hostname: yiff-media.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.5
  yiff.rest:
    <<: *shared
    container_name: yiff.rest
    volumes:
      - ./src/config/ssl:/app/ssl
      - /etc/hostname:/data/hostname:ro
      - ./data/shared:/data
      - ./src/sites/yiff.rest/views:/app/views
      - ./data/cache/yiff.rest:/data/cache
      - /var/www/sites/yiff.rest:/app/public
      - /var/www/sites/yiff.media/V2:/app/public/V2
      - /var/www/e621-thumb:/data/e621-thumb
      - /var/www/e621-thumbnails:/data/e621-thumbnails
    environment:
      SITE: yiff.rest
      FFMPEG_PATH: /usr/bin/ffmpeg
      FFPROBE_PATH: /usr/bin/ffprobe
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    hostname: yiff-rest.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.6
  yiff.rocks:
    <<: *shared
    container_name: yiff.rocks
    volumes:
      - ./src/config/ssl:/app/ssl
      - /etc/hostname:/data/hostname:ro
      - ./data/shared:/data
      - ./src/sites/yiff.rocks/views:/app/views
      - ./data/cache/yiff.rocks:/data/cache
      - /var/www/sites/yiff.rocks:/app/public
      - /var/www/sites/yiff.media/V2:/app/public/V2
    environment:
      SITE: yiff.rocks
    hostname: yiff-rocks.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.7
  oceanic.ws:
    <<: *shared
    container_name: oceanic.ws
    volumes:
      - ./src/config/ssl:/app/ssl
      - /etc/hostname:/data/hostname:ro
      - ./data/shared:/data
      - ./src/sites/oceanic.ws/views:/app/views
      - ./data/cache/oceanic.ws:/data/cache
      - /var/www/sites/oceanic.ws:/app/public
      - /var/www/oceanic-docs:/data/docs
    environment:
      SITE: oceanic.ws
    hostname: owo-whats-this-dev.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.8
  imgen:
    image: registry.local/imgen
    container_name: imgen.websites
    volumes:
      - ./src/imgen:/app
    restart: always
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :3621 || exit 1
    depends_on:
      rethinkdb:
        condition: service_started
      redis:
        condition: service_healthy
      yiff.rest:
        condition: service_healthy
    hostname: imgen.websites.containers.local
    deploy:
        resources:
            limits:
              memory: 2048M
            reservations:
              memory: 512M
    networks:
      default:
        ipv4_address: 172.19.2.251
  mariadb:
    image: mariadb
    container_name: mariadb.websites
    volumes:
      - ./data/db:/var/lib/mysql
    deploy:
        resources:
            limits:
              memory: 2048M
            reservations:
              memory: 512M
    environment:
      MYSQL_ROOT_PASSWORD: "$MARIADB_ROOT_PASSWORD"
    restart: always
    healthcheck:
      interval: 5s
      timeout: 2s
      test: mysqladmin --user=root --password=$$MYSQL_ROOT_PASSWORD ping
    hostname: mariadb.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.252
  rethinkdb:
    image: rethinkdb
    command: rethinkdb --bind all -n rdb
    container_name: rethinkdb.websites
    volumes:
      - ./data/rethink:/data
    deploy:
        resources:
            limits:
              memory: 1024M
            reservations:
              memory: 128M
    restart: always
    hostname: rethinkdb.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.253
  redis:
    image: redis:alpine
    command: redis-server --disable-thp yes --supervised no --bind 0.0.0.0 --requirepass "$REDIS_PASSWORD"
    container_name: redis.websites
    volumes:
      - ./data/redis:/data
    deploy:
        resources:
            limits:
              memory: 2048M
            reservations:
              memory: 512M
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
    restart: always
    hostname: redis.websites.containers.local
    networks:
      default:
        ipv4_address: 172.19.2.254
networks:
  default:
    name: websites
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.2.0/24
          gateway: 172.19.2.1
