ALTER TABLE `yiffyapi2`.`usage`
    CHANGE raw_text method TINYTEXT NOT NULL,
	CHANGE timestamp path TINYTEXT NOT NULL,
	MODIFY id BIGINT AUTO_INCREMENT NOT NULL,
	ADD timestamp TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3);
