ALTER TABLE `yiffyapi2`.`usage`
    CHANGE raw_text method TINYTEXT NOT NULL,
	CHANGE timestamp path TINYTEXT NOT NULL,
	CHANGE id BIGINT AUTO_INCREMENT NOT NULL,
	ADD timestamp TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL;

ALTER TABLE `websites3`.`usage`
	CHANGE id BIGINT AUTO_INCREMENT NOT NULL;
