ALTER TABLE `yiffyapi2`.`apikeys`
	ADD `window_long`   SMALLINT  UNSIGNED NOT NULL DEFAULT 10000,
	ADD `limit_long`    SMALLINT  UNSIGNED NOT NULL DEFAULT 12,
	ADD `window_short`  SMALLINT  UNSIGNED NOT NULL DEFAULT 2000,
	ADD `limit_short`   SMALLINT  UNSIGNED NOT NULL DEFAULT 4;
