CREATE TABLE `e621`.`posts` (
    `id`                INT         NOT NULL PRIMARY KEY,
    `uploader_id`       INT,
    `created_at`        TINYTEXT    NOT NULL,
    `md5`               CHAR(32),
    `sources`           MEDIUMTEXT  NOT NULL,
    `rating`            CHAR(1)     NOT NULL,
    `width`             INT         NOT NULL,
    `height`            INT         NOT NULL,
    `tags`              TEXT        NOT NULL,
    `locked_tags`       TEXT,
    `fav_count`         INT         NOT NULL,
    `file_ext`          TINYTEXT    NOT NULL,
    `parent_id`         INT,
    `change_seq`        INT         NOT NULL,
    `approver_id`       INT,
    `file_size`         INT         NOT NULL,
    `comment_count`     INT         NOT NULL,
    `description`       MEDIUMTEXT,
    `duration`          INT,
    `updated_at`        TINYTEXT,
    `is_deleted`        BOOLEAN     NOT NULL,
    `is_pending`        BOOLEAN     NOT NULL,
    `is_flagged`        BOOLEAN     NOT NULL,
    `score`             INT         NOT NULL,
    `up_score`          INT         NOT NULL,
    `down_score`        INT         NOT NULL,
    `is_rating_locked`  BOOLEAN     NOT NULL,
    `is_status_locked`  BOOLEAN     NOT NULL,
    `is_note_locked`    BOOLEAN     NOT NULL,
    `animated`          BOOLEAN     NOT NULL DEFAULT FALSE,
    `animated_png`      BOOLEAN     NOT NULL DEFAULT FALSE,
	-- Indexes
	INDEX               `rating`                        (`rating`),
	INDEX               `is_deleted`                    (`is_deleted`),
	INDEX               `is_deleted.rating`             (`is_deleted`, `rating`),
	INDEX               `is_pending`                    (`is_pending`),
	INDEX               `is_pending.rating`             (`is_pending`, `rating`),
	INDEX               `is_flagged`                    (`is_flagged`),
	INDEX               `is_flagged.rating`             (`is_flagged`, `rating`),
	INDEX               `is_rating_locked`              (`is_rating_locked`),
	INDEX               `is_rating_locked.rating`       (`is_rating_locked`, `rating`),
	INDEX               `is_status_locked`              (`is_status_locked`),
	INDEX               `is_status_locked.rating`       (`is_status_locked`, `rating`),
	INDEX               `is_note_locked`                (`is_note_locked`),
	INDEX               `is_note_locked.rating`         (`is_note_locked`, `rating`),
	INDEX               `approver_id`                   (`approver_id`),
	INDEX               `uploader_id`                   (`uploader_id`),
	INDEX               `file_ext`                                (`file_ext`),
	INDEX               `file_ext.rating`                         (`file_ext`, `rating`),
	INDEX               `file_ext.is_deleted`                     (`file_ext`, `is_deleted`),
	INDEX               `file_ext.is_deleted.rating`              (`file_ext`, `is_deleted`, `rating`),
	INDEX               `file_ext.animated_png`                   (`file_ext`, `animated_png`),
	INDEX               `file_ext.rating.animated_png`            (`file_ext`, `rating`, `animated_png`),
	INDEX               `file_ext.is_deleted.animated_png`        (`file_ext`, `is_deleted`, `animated_png`),
	INDEX               `file_ext.is_deleted.rating.animated_png` (`file_ext`, `is_deleted`, `rating`, `animated_png`)
)
